name: alagaaiv100
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  generative_ai_dart: ^0.1.2
  overlay_support: ^2.1.0
  google_generative_ai: ^0.4.7
  flutter_accessibility_service: ^1.0.0
  drag_ball: ^2.0.1
  flutter_dotenv: ^5.1.0
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logoNoText.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
