// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVxFkU6wkO4RlHaVhvp5P6n4cyiY3FqQ',
    appId: '1:262980409120:web:9c6a9c8409d61649472945',
    messagingSenderId: '262980409120',
    projectId: 'alagaaiv100-4a80e',
    authDomain: 'alagaaiv100-4a80e.firebaseapp.com',
    storageBucket: 'alagaaiv100-4a80e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7j46dj30IEMJ2Y-wV7bxs_LUE9lXiIGQ',
    appId: '1:262980409120:android:b134c06f2cd24bb1472945',
    messagingSenderId: '262980409120',
    projectId: 'alagaaiv100-4a80e',
    storageBucket: 'alagaaiv100-4a80e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIVfA1rOgT1kY7uVL9-UTAUgLc8TLHlk',
    appId: '1:262980409120:ios:57fd57629d279f6e472945',
    messagingSenderId: '262980409120',
    projectId: 'alagaaiv100-4a80e',
    storageBucket: 'alagaaiv100-4a80e.firebasestorage.app',
    iosBundleId: 'com.example.alagaaiv100',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaIVfA1rOgT1kY7uVL9-UTAUgLc8TLHlk',
    appId: '1:262980409120:ios:57fd57629d279f6e472945',
    messagingSenderId: '262980409120',
    projectId: 'alagaaiv100-4a80e',
    storageBucket: 'alagaaiv100-4a80e.firebasestorage.app',
    iosBundleId: 'com.example.alagaaiv100',
  );
}
